name: fastapi_template

services:
  backend:
    build: .
    command: sh -c "alembic upgrade head && fastapi run app --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.1-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    networks:
      - network

volumes:
  pg_data:

networks:
  network:
    name: network