name: Generate page docs

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: |
          cp .env.dist .env
          docker-compose build

      - name: Run Docker
        run: |
          docker-compose up -d

      - name: Create docs directory if it doesn't exist
        run: |
          if [ ! -d "docs" ]; then
            mkdir -p docs
          fi

      - name: Fetch page docs
        run: |
          until $(curl -o docs/index.html --silent --head --fail http://0.0.0.0:8000/api/docs); do
            sleep 1
          done

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/index.html
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_with_lease: true
