name: Generate page docs

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: |
          cp .env.dist .env
          docker-compose build

      - name: Run Docker
        run: |
          docker-compose up -d

      - name: Fetch page docs
        run: |
          until $(curl -o docs/openapi.json --silent --fail http://0.0.0.0:8000/api/openapi.json); do
            sleep 1
          done

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
